services:
  mysql:
    image: mysql:latest
    container_name: mvc-assignment-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
    restart: always
    networks:
      - hungry-net
  go:
    image: adiqtpi/mvc_foodopia:latest
    container_name: mvc-assignment-go
    environment:
      - SERVER_PORT=9080
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_pwd
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - SESSIONS_SECRET=${SESSIONS_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SEED_DB=${SEED_DUMMY_DATA}
      - DOCKER_ENV=true
    ports:
      - "9000:9000"
      - "9080:9080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - hungry-net

networks:
  hungry-net:
    driver: bridge